##### WSO-Config WSO 2.0 #####

- name: Install ufw
  dnf:
    name: ufw
    state: present

- name: Set logging to high
  ansible.builtin.lineinfile:
    path: /etc/ufw/ufw.conf
    regexp: '^LOGLEVEL='
    line: 'LOGLEVEL=high'

- name: Allow loopback
  community.general.ufw:
    rule: allow
    direction: in
    interface: lo

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow NTP
  ufw:
    rule: allow
    port: 123
    proto: udp

- name: Allow Grafana
  ufw:
    rule: allow
    port: 3000
    proto: tcp
    from_ip: 192.168.1.0/24 # local

- name: Allow Prometheus
  ufw:
    rule: allow
    port: 9090
    proto: tcp
    from_ip: 192.168.1.0/24 # local

- name: Allow Webmin
  ufw:
    rule: allow
    port: 10000
    proto: tcp
    from_ip: 192.168.1.0/24 # local

- name: Allow Jenkins
  ufw:
    rule: allow
    port: 8080
    proto: tcp

- name: Allow Mailman web interface
  ufw:
    rule: allow
    port: 8000
    proto: tcp

- name: Allow Mailman SMTP (inbound mail)
  ufw:
    rule: allow
    port: 25
    proto: tcp

- name: Allow Mailman submission (auth SMTP)
  ufw:
    rule: allow
    port: 587
    proto: tcp

- name: Allow Mailman IMAP/POP (if we're hosting mailboxes)
  ufw:
    rule: allow
    port: 993
    proto: tcp

- name: Enable and start ufw job
  systemd:
    name: ufw
    enabled: yes
    state: started

- name: Enable ufw kernel-level firewall
  community.general.ufw:
    state: enabled
    policy: deny
    # note that "log" here logs fails, not other stuff
    log: true

- name: Reload ufw policy, if we changed anything
  ansible.builtin.shell: ufw reload
    
