##### WSO-Config WSO 2.0 #####

- name: Install ufw
  dnf:
    name: ufw
    state: present

- name: Enable and start ufw
  systemd:
    name: ufw
    enabled: yes
    state: started

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    # note that "log" here logs fails, not other stuff
    log: true

- name: Turn on UFW logging
  community.general.ufw:
    logging: "high"

- name: Unblock common ports in UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'
    - '123'

    
    
