##### WSO-Config WSO 2.0 #####

- name: Install mailman3
  dnf:
    name: mailman3
    state: present
  when: inventory_hostname == 'wso_prod'

- name: Install postfix
  dnf:
    name: postfix
    state: present
  when: inventory_hostname == 'wso_prod'

- name: Install hyperkitty
  dnf:
    name: hyperkitty
    state: present
  when: inventory_hostname == 'wso_prod'

# TODO: need to configure mailman3

- name: Enable and start mailman3
  systemd:
    name: mailman3
    enabled: yes
    state: started
  when: inventory_hostname == 'wso_prod'

# TODO: do we even want hyperkitty?
