##### WSO-Config WSO 2.0 #####

- name: Check if Webmin repo is already present
  ansible.builtin.stat:
    path: /etc/yum.repos.d/webmin-stable.repo
  register: webmin_repo

- name: Install Webmin the canonical way
  # without forcing, webmin won't install. don't remove that -f!
  ansible.builtin.shell: |
    curl -o /root/ansible/webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
    sh /root/ansible/webmin-setup-repo.sh -f
  when: not webmin_repo.stat.exists

- name: Install Webmin using new repos
  ansible.builtin.dnf:
    name: webmin
    state: present

# TODO: when we get SSL running on server, probs turn this off
# TODO: Webmin's default SSL cert is very broken. We'll need to fix that in the future
- name: Disable mandatory SSL requirement
  ansible.builtin.lineinfile:
    path: /etc/webmin/miniserv.conf
    regexp: '^ssl='
    line: 'ssl=0'

- name: Enable and start webmin
  ansible.builtin.systemd:
    name: webmin
    enabled: true
    state: started





