##### WSO-Config WSO 2.0 #####

# this makes all our downloads faster, so do this first.
- name: Tweak dnf.conf
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: fastestmirror, value: true }
    - { option: max_parallel_downloads, value: 10 }
    - { option: defaulttrue, value: true }

# need to do this first to get latest package lists
- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true

# enable Extra Packages for Enterprise Linux
- name: Enable EPEL repo
  ansible.builtin.dnf:
    name: epel-release
    state: present

# now time to grab RPM fusion
- name: Get RPM Fusion keys
  ansible.builtin.dnf:
    name: distribution-gpg-keys
    state: present

- name: Add RPM Fusion keys to keystore
  ansible.builtin.shell: |
    rpmkeys --import /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-el-$(rpm -E %rhel)
    rpmkeys --import /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-el-$(rpm -E %rhel)

- name: Enable RPM Fusion repository
  ansible.builtin.shell: dnf -y --setopt=localpkg_gpgcheck=1 install  https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm

# Refresh now that we have new repos
- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true



