##### WSO-Config WSO 2.0 #####
# Note that this is only for installing the servers,
# not for actually configuring them. For that, use a wso-specific task

- name: Install mysql-server
  dnf:
    name: mysql-server
    state: present

- name: Enable and start mysqld
  systemd:
    name: mysqld
    enabled: yes
    state: started
    
