##### WSO-Config WSO 2.0 #####
# Note that this is only for installing the servers,
# not for actually configuring them. For that, use a wso-specific task

- name: Install mysql-server
  dnf:
    name: mysql-server
    state: present
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Enable and start mysqld
  systemd:
    name: mysqld
    enabled: yes
    state: started
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'
    
