##### WSO-Config WSO 2.0 #####
- hosts: all
  # turn off in production, some errors are natural and fine
  # but it's useful to keep this on for debugging reasons
  ignore_errors: no
  become: yes
  roles:
    # essential configuration
    - branding
    - ensure_packages
    - core_packages
    - hardening
    - networking
    - fresh_kernel

    # services
    - service_auditd
    - service_haveged
    - service_zram
    - service_ufw
    - service_fail2ban
    - service_backup
    - service_dnfauto
    - service_apache
    - service_webmin
    - service_grafana
    - service_prometheus
    - service_mailman3
    - service_mysql
    - service_oomd
    - service_jenkins
    - service_mediawiki
    - service_minecraft # TODO: edit on prod
    
    # service_clamd exists, but is highly buggy and is thus removed.
    # if you want to use it, you'll need to fix it yourself.

    # wso software
    - wso_cronjobs
    - wso_manpage
    
    # users
    - user_wso
    - user_trivia
    - user_oit
