##### WSO-Config WSO 2.0 #####
- hosts: all
  # turn off in production, some errors are natural and fine
  # but it's useful to keep this on for debugging reasons
  ignore_errors: no
  become: yes
  roles:
    - service_ufw
    # essential configuration
    - branding
    - ensure_packages
    - core_packages
    - hardening

    # services
    - service_backup
    - service_fail2ban
    #- service_clamd
    - service_webmin
    - service_zram
    - service_grafana
    - service_prometheus
    - service_oomd

    # wso software
    - wso_cronjobs
    
    # users
    - user_wso
    - user_trivia
    - user_oit
