##### WSO-Config WSO 2.0 #####
- name: WSO Server Configuration
  hosts: all
  # turn off in production, some errors are natural and fine
  # but it's useful to keep this on for debugging reasons
  ignore_errors: false
  become: true
  roles:
    # essential configuration
    - special_branding
    - special_ensure_packages
    - special_core_packages
    - special_hardening
    - special_networking
    - special_fresh_kernel

    # TODO: add a service for uptime-kuma to replace cachet

    # services
    - service_auditd
    - service_tuned
    - service_zram
    - service_firewalld
    - service_fail2ban
    - service_backup
    - service_dnfauto
    - service_nginx
    - service_webmin
    - service_grafana
    - service_prometheus
    - service_docker
    - service_mailman
    - service_spamassassin
    - service_postfix
    - service_mariadb
    - service_oomd
    - service_jenkins
    - service_mediawiki
    - service_minecraft
    - service_foundry    
    - service_clamd    

    # wso software
    - wso_cronjobs
    - wso_manpage

    # users
    - user_wso
    - user_trivia
    - user_oit

    - special_cleanup
