##### WSO-Config WSO 2.0 #####

- name: Install clamd
  ansible.builtin.dnf:
    name: "{{ clamd_packages }}"
    state: present
  vars:
    clamd_packages:
      - clamav
      - clamav-update
      - clamd

- name: Ensure clamd config exists
  ansible.builtin.copy:
    src: /etc/clamd.d/scan.conf
    dest: /etc/clamd.d/scan.conf
    remote_src: yes
    force: no
    
- name: Ensure freshclam config exists
  ansible.builtin.copy:
    src: /etc/freshclam.conf
    dest: /etc/freshclam.conf
    remote_src: yes
    force: no

- name: Create virus database dir
  ansible.builtin.file:
    path: /var/lib/clamav
    state: directory
    owner: clamupdate
    group: clamupdate
    mode: '0755'

- name: Run freshclam manually if no DB exists
  ansible.builtin.command: freshclam
  when: not (lookup('ansible.builtin.fileglob', '/var/lib/clamav/*.cvd', errors='ignore'))
  register: clamav_db_update
  changed_when: "'Downloading' in clamav_db_update.stdout"

- name: Enable and start clamd
  ansible.builtin.systemd:
    name: clamd@scan
    enabled: yes
    state: started

# TODO: we want to make this better
# https://docs.clamav.net/manual/Usage/Configuration.html

