##### WSO-Config WSO 2.0 #####

# force this on
- name: Enable SELinux enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

# too many of these. go check the values in ../../vars/main.yml
- name: Harden sysctl
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ hardening_sysctls }}"

- name: Harden weak permissions
  ansible.builtin.shell: chmod 700 /boot /usr/src /lib/modules /usr/lib/modules

- name: Harden loadable kernel modules
  ansible.builtin.copy:
  # this list needs to be manually checked if you're doing something weird
    src: module-blacklist
    dest: /etc/modprobe.d/blacklist
    mode: 0700

- name: Disable insecure service kdump
  ansible.builtin.systemd:
    name: kdump
    enabled: false
    state: stopped

# TODO: tighten security on PAM and /etc/shadow. we need more secure password gen
    





