global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /prometheus/metrics

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
