##### WSO-Config WSO 2.0 #####
- name: Create backup directory (backup server)
  ansible.builtin.file:
    path: /backup
    state: directory
    mode: '0755'
  when: inventory_hostname == 'wso_backup'

- name: Create remote directory (remote server)
  ansible.builtin.file:
    path: /remote
    state: directory
    mode: '0755'
  when: inventory_hostname == 'wso_backup'

- name: Create backup directory (prod server)
  ansible.builtin.file:
    path: /backup
    state: directory
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Generate Borg ssh keypair for root
  command: ssh-keygen -t ed25519 -f /root/.ssh/borg_key -N ''
  args:
    creates: /root/.ssh/borg_key
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Fetch Borg public key
  slurp:
    src: /root/.ssh/borg_key.pub
  register: borg_pubkey_raw
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Set Borg pubkey string
  set_fact:
    borg_pubkey: "{{ borg_pubkey_raw.content | b64decode }}"
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Ensure /root/.ssh exists
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Authorize peer Borg key on backup
  authorized_key:
    user: root
    key: "{{ hostvars['wso_prod'].borg_pubkey }}"
    comment: "Borg key"
  when: inventory_hostname == 'wso_backup'

- name: Authorize peer Borg key on prod
  authorized_key:
    user: root
    key: "{{ hostvars['wso_backup'].borg_pubkey }}"
    comment: "Borg key"
  when: inventory_hostname == 'wso_prod'

- name: Ensure SSH config exists
  file:
    path: /root/.ssh/config
    state: touch
    mode: '0600'
    owner: root
    group: root
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Add SSH identity config for peer
  blockinfile:
    path: /root/.ssh/config
    create: yes
    owner: root
    group: root
    mode: '0600'
    block: |
      Host wso_backup
        IdentityFile /root/.ssh/borg_key
        User root
        IdentitiesOnly yes

      Host wso_prod
        IdentityFile /root/.ssh/borg_key
        User root
        IdentitiesOnly yes
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: enable user_allow_other in fuse.conf
  lineinfile:
    path: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: 'user_allow_other'
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

# - name: deploy sshfs mount on backup (mounts prod:/ -> /remote)
#   template:
#     src: sshfs-automount.service.j2
#     dest: /etc/systemd/system/remote.mount
#     mode: '0644'
#   vars:
#     remote_host: "{{ hostvars['wso_prod'].host_name }}"
#     remote_path: "/"
#     local_path: "/remote"
#   when: inventory_hostname == 'wso_backup'

# - name: deploy sshfs mount on prod (mounts backup:/backup -> /backup)
#   template:
#     src: sshfs-automount.service.j2
#     dest: /etc/systemd/system/backup.mount
#     mode: '0644'
#   vars:
#     remote_host: "{{ hostvars['wso_backup'].host_name }}"
#     remote_path: "/backup"
#     local_path: "/backup"
#   when: inventory_hostname == 'wso_prod'

# - name: enable and start sshfs mount unit
#   systemd:
#     name: "{{ local_path | regex_replace('^/', '') }}.mount"
#     enabled: yes
#     state: started
#   when: local_path is defined

- name: Copy backup shell script
  ansible.builtin.copy:
    src: backer-upper.sh
    dest: /root/
    force: yes
  when: inventory_hostname == 'wso_prod'

- name: Make Borg cronjob log backup
  ansible.builtin.cron:
     name: Borg log backup
     #disabled: true
     hour: "1"
     minute: "0"
     job: "/bin/bash -l -c /root/backer-upper.sh"
  when: inventory_hostname == 'wso_prod'


  
