##### WSO-Config WSO 2.0 #####
- name: Install Borg-backup
  ansible.builtin.dnf:
    name: borgbackup
    state: present
  when: inventory_hostname == 'wso_prod'
  
- name: Copy backup shell script
  ansible.builtin.copy:
    src: backer-upper.sh
    dest: /root/ansible/
    force: true
  when: inventory_hostname == 'wso_prod'

- name: Check if Borg repo is already initialized
  ansible.builtin.shell: yes | borg info /wsobackup
  register: borg_repo_check
  ignore_errors: true
  when: inventory_hostname == 'wso_prod'

- name: Initialize Borg repo if not present
  ansible.builtin.command: borg init --encryption=none /wsobackup
  when: borg_repo_check.rc != 0
  
- name: Make backup script executable
  ansible.builtin.shell: chmod +x /root/ansible/backer-upper.sh
  when: inventory_hostname == 'wso_prod'
  
- name: Make Borg cronjob log backup
  ansible.builtin.cron:
     name: "Borg log backup"
     disabled: false
     hour: "1"
     minute: "0"
     user: root
     job: "/bin/bash -l -c /root/ansible/backer-upper.sh >> /var/log/borg-backup.log 2>&1"
  when: inventory_hostname == 'wso_prod'

