##### WSO-Config WSO 2.0 #####

- name: Install postfix
  ansible.builtin.package:
    name: postfix
    state: present
  when: inventory_hostname == 'wso_prod'

- name: Enable postfix
  ansible.builtin.systemd:
    name: postfix
    enabled: true
    state: started
  when: inventory_hostname == 'wso_prod'

# TODO: you still need to configure postfix,
# so that it sends mail the way you want AND bans spam to the mod queue
