##### WSO-Config WSO 2.0 #####

# force this on
- name: Enable SELinux enforcing
  selinux:
    policy: targeted
    state: enforcing

# too many of these. go check the values in ../../vars/main.yml
- name: Harden sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ sysctl_hardening }}"

- name: Harden weak permissions
  shell: chmod 700 /boot /usr/src /lib/modules /usr/lib/modules

- name: Harden loadable kernel modules
  ansible.builtin.copy:
  # this list needs to be manually checked if you're doing something weird
    src: module-blacklist
    dest: /etc/modprobe.d/blacklist
    mode: 0700

- name: Disable insecure service kdump
  systemd:
    name: kdump
    enabled: no
    state: stopped

# TODO: tighten security on PAM and /etc/shadow. we need more secure password gen
    





