##### WSO-Config WSO 2.0 #####

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Enable and start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Unbreak nginx SELinux permissions
  ansible.builtin.shell: setsebool -P httpd_can_network_connect 1

- name: Copy nginx master config file
  ansible.builtin.copy:
    src: services.conf
    dest: /etc/nginx/conf.d/services.conf
    force: true
  when: inventory_hostname == 'wso_prod'

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

# note that you'll need to move the SSL secrets yourself. too sensitive to store
# them on GitHub. you'll figure it out.
