##### WSO-Config WSO 2.0 #####

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Enable and start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Unbreak nginx SELinux permissions
  ansible.builtin.shell: setsebool -P httpd_can_network_connect 1
