##### WSO-Config WSO 2.0 #####

# We only want ONE GUI (on prod),
# but we can scrape all the other machines.
# might want the stats

- name: Download Prometheus
  ansible.builtin.get_url:
  # TODO: change this on prod to the right arch
    url: https://github.com/prometheus/prometheus/releases/download/v3.5.0/prometheus-3.5.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz
  when: inventory_hostname == 'wso_prod'

- name: Download Prometheus Node Exporter
  ansible.builtin.get_url:
  # TODO: change this on prod to the right arch
    url: https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz
    dest: /tmp/node.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: true
  when: inventory_hostname == 'wso_prod'

- name: Extract Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node.tar.gz
    dest: /tmp
    remote_src: true

- name: Move Prometheus binary
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/prometheus-3.5.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Move Prometheus Node Exporter binary
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/node_exporter-1.9.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'

- name: Install Prometheus service
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Create Prometheus directories
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    recurse: true
  when: inventory_hostname == 'wso_prod'

- name: Install Prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Install Prometheus Node Exporter service
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: '0755'
  
- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: /sbin/nologin
    create_home: false
  when: inventory_hostname == 'wso_prod'

- name: Create Prometheus Node Exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin
    create_home: false

- name: Make Prometheus data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
   - /etc/prometheus
   - /var/lib/prometheus
  when: inventory_hostname == 'wso_prod'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable & start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
  when: inventory_hostname == 'wso_prod'

- name: Enable & start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  when: inventory_hostname == 'wso_prod'

# TODO: configure Prometheus for wso-go
