##### WSO-Config WSO 2.0 #####

# We only want ONE GUI (on prod),
# but we can scrape all the other machines.
# might want the stats

- name: Download Prometheus
  ansible.builtin.get_url:
  # TODO: change this on prod to the right arch
    url: https://github.com/prometheus/prometheus/releases/download/v3.5.0/prometheus-3.5.0.linux-arm64.tar.gz
    dest: /tmp/prometheus.tar.gz
  when: inventory_hostname == 'wso_prod'

- name: Download Prometheus Node Exporter
  ansible.builtin.get_url:
  # TODO: change this on prod to the right arch
    url: https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-arm64.tar.gz
    dest: /tmp/node.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: true
  when: inventory_hostname == 'wso_prod'

- name: Extract Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node.tar.gz
    dest: /tmp
    remote_src: true

- name: Move Prometheus binary
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/prometheus-3.5.0.linux-arm64/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Move Prometheus Node Exporter binary
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/node_exporter-1.9.1.linux-arm64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'

- name: Install Prometheus service
  ansible.builtin.copy:
    src: prometheus.service
    dest: /usr/lib/systemd/system/prometheus.service
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Install Prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: '0755'
  when: inventory_hostname == 'wso_prod'

- name: Install Prometheus Node Exporter service
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service
    mode: '0755'
  
- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: /sbin/nologin
  when: inventory_hostname == 'wso_prod'

- name: Create Prometheus Node Exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin

- name: Make Prometheus data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
   - /etc/prometheus
   - /var/lib/prometheus
  when: inventory_hostname == 'wso_prod'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable & start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
  when: inventory_hostname == 'wso_prod'

- name: Enable & start Prometheus
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started

- name: Deploy Prometheus vhost
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/prometheus.conf
    force: true
    content: |
         server {
             listen 80;
             server_name prometheus.local;


             location = /prometheus {
                      return 302 /prometheus/;
             }

             location /prometheus/ {
                 proxy_pass http://localhost:9090/;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header X-Forwarded-Proto $scheme;
             }
             
             access_log /var/log/nginx/prometheus_access.log;
             error_log /var/log/nginx/prometheus_error.log;
         }
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

# TODO: configure Prometheus
