##### WSO-Config WSO 2.0 #####

# I don't know why they're named so weirdly
- name: Install Prometheus
  ansible.builtin.dnf:
    name: golang-github-prometheus
    state: present

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Install Prometheus Node Exporter
  ansible.builtin.dnf:
    name: golang-github-prometheus-node-exporter
    state: present

- name: Enable and start Prometheus Node Exporter
  systemd:
    name: prometheus-node-exporter
    enabled: yes
    state: started

# TODO: configure Prometheus
