##### WSO-Config WSO 2.0 #####
# IMPORTANT NOTE:
# Jenkins uses 8080, so check docker-compose.yml for correct port

- name: Add Mailman group
  ansible.builtin.group:
    name: mailman
    gid: 1984
    state: present
  when: inventory_hostname == 'wso_prod'

- name: Create Mailman user for security
  ansible.builtin.user:
     name: mailman
     comment: Mailman Server User
     uid: 1984 # because why not
     shell: /bin/false
     group: mailman
     create_home: false
     state: present
  when: inventory_hostname == 'wso_prod'

- name: Get Python dependency for Ansible Docker
  ansible.builtin.dnf:
    name: python3-requests
    state: present
  when: inventory_hostname == 'wso_prod'

- name: Create Mailman root directory
  ansible.builtin.file:
     path: /opt/mailman
     state: directory
     owner: mailman
     group: mailman
     mode: '0750'
  when: inventory_hostname == 'wso_prod'

- name: Create Mailman service directory (1/2)
  ansible.builtin.file:
     path: /opt/mailman/core
     state: directory
     owner: mailman
     group: mailman
     mode: '0750'
  when: inventory_hostname == 'wso_prod'

- name: Create Mailman service directory (2/2)
  ansible.builtin.file:
     path: /opt/mailman/web
     state: directory
     owner: mailman
     group: mailman
     mode: '0750'
  when: inventory_hostname == 'wso_prod'

- name: Git checkout Docker Mailman
  ansible.builtin.git:
    repo: 'https://github.com/maxking/docker-mailman'
    dest: /opt/mailman/docker-mailman
    update: false
    version: v0.5.2
  when: inventory_hostname == 'wso_prod'

- name: Fix perms for Docker Mailman
  ansible.builtin.shell: chown -R mailman:mailman /opt/mailman
  when: inventory_hostname == 'wso_prod'
  
- name: Install systemd service unit for Mailman Docker Compose
  ansible.builtin.copy:
    src: mailman.service
    force: true
    dest: /etc/systemd/system/mailman.service
    mode: '0644'
  when: inventory_hostname == 'wso_prod'

- name: Reload systemd to register mailman service
  ansible.builtin.command: systemctl daemon-reload
  when: inventory_hostname == 'wso_prod'

- name: Enable and start Mailman service
  ansible.builtin.systemd:
    name: mailman
    enabled: true
    state: started
  when: inventory_hostname == 'wso_prod'

