##### WSO-Config WSO 2.0 #####

- name: Install MediaWiki dependencies
  ansible.builtin.dnf:
    name:
      - php
      - php-mysqlnd
      - php-xml
      - php-intl
      - php-mbstring
      - php-curl
      - php-gd
      - php-apcu
    state: present
    update_cache: true
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Ensure proper subdirs exist
  ansible.builtin.file:
    path: /srv/www/
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Create MediaWiki directory
  ansible.builtin.file:
    path: /srv/www/wiki
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Download MediaWiki
  ansible.builtin.get_url:
    url: https://releases.wikimedia.org/mediawiki/1.41/mediawiki-1.41.1.tar.gz
    dest: /tmp/mediawiki.tar.gz
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Extract MediaWiki
  ansible.builtin.unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: /srv/www/wiki
    remote_src: true
    creates: /srv/www/wiki/mediawiki
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Fix the extracted MediaWiki
  ansible.builtin.command: mv /srv/www/wiki/mediawiki/* /srv/www/wiki/
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'
  
- name: Set SELinux context on /srv and subdirs for Nginx
  ansible.builtin.command: semanage fcontext -a -t httpd_sys_content_t "{{ item }}(/.*)?"
  loop:
    - /srv
    - /srv/www
    - /srv/www/wiki
  changed_when: false
  ignore_errors: true  # semanage errors if already exists
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Restore SELinux context on /srv and subdirs
  ansible.builtin.command: restorecon -Rv /srv /srv/www /srv/www/wiki
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Ensure /srv/www/wiki has o+x for Nginx directory access
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - /srv
    - /srv/www
    - /srv/www/wiki
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Enable Nginx access boolean for user content
  ansible.builtin.command: setsebool -P httpd_read_user_content 1
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Set permissions with shell (recursive chown)
  ansible.builtin.shell: chown -R nginx:nginx /srv/www/wiki/
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_dev'

