##### WSO-Config WSO 2.0 #####
# TODO: should enhance with better logging of the interesting stuff

- name: Install auditd
  ansible.builtin.dnf:
    name: audit
    state: present

- name: Enable and start auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started
