##### WSO-Config WSO 2.0 #####

- name: Install spamassassin
  ansible.builtin.package:
    name: spamassassin
    state: present
  when: inventory_hostname == 'wso_prod'

# - name: Install systemd service unit for spamassassin-update
#   ansible.builtin.copy:
#     src: spamassassin-update.service
#     force: true
#     dest: /usr/lib/systemd/system/spamassassin-update.service
#     mode: '0644'
#   when: inventory_hostname == 'wso_prod'

# - name: Install systemd timer unit for spamassassin-update
#   ansible.builtin.copy:
#     src: spamassassin-update.timer
#     force: true
#     dest: /usr/lib/systemd/system/spamassassin-update.timer
#     mode: '0644'
#   when: inventory_hostname == 'wso_prod'

- name: Enable spamassassin
  ansible.builtin.systemd:
    name: spamassassin
    enabled: true
    state: started
  when: inventory_hostname == 'wso_prod'

# - name: Enable spamassassin-update timer
#   ansible.builtin.systemd:
#     name: spamassassin-update.timer
#     enabled: true
#     state: started
#   when: inventory_hostname == 'wso_prod'

# TODO: Okay, this gets spamd working, but it doesn't configure it.
# You need to edit the service file to configure this.
# Otherwise, it won't do anything.
