##### WSO-Config WSO 2.0 #####

- name: Download Jenkins GPG signing key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
    dest: /tmp/jenkins-gpg.key

- name: Import Jenkins GPG signing key
  ansible.builtin.shell: sudo rpm --import /tmp/jenkins-gpg.key

- name: Copy Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.repo
    force: true
    dest: /etc/yum.repos.d/jenkins.repo

- name: Update DNF cache after adding repo
  ansible.builtin.dnf:
    update_cache: true

- name: Install Jenkins dependency fontconfig
  ansible.builtin.dnf:
    name: fontconfig
    state: present

- name: Install Jenkins dependency java-21-openjdk
  ansible.builtin.dnf:
    name: java-21-openjdk
    state: present

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  ansible.builtin.systemd:
    name: jenkins
    enabled: true
    state: started
