##### WSO-Config WSO 2.0 #####

- name: Install zram-generator
  ansible.builtin.dnf:
    name: zram-generator
    state: present

- name: Load zram kernel module
  ansible.builtin.shell: modprobe zram

- name: Ensure zram stays on
  ansible.builtin.copy:
    dest: /etc/modules-load.d/zram.conf
    content: "zram"
        
- name: Configure zram block devices
  ansible.builtin.copy:
    src: zram_generator.conf
    dest: /etc/systemd/zram-generator.conf
    backup: true

- name: Enable and start zram-generator
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0
    enabled: true
    state: started
