##### WSO-Config WSO 2.0 #####

- name: Install dependencies
  ansible.builtin.package:
    name:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: present

- name: Add Docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Update DNF cache after adding repo
  ansible.builtin.dnf:
    update_cache: true
  when: inventory_hostname == 'wso_prod' or inventory_hostname == 'wso_backup'

- name: Install Docker and Docker Compose plugin
  ansible.builtin.dnf:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    state: present

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
