.\" Manpage for wso-backend.
.\" To install locally, run:
.\" install -g 0 -o 0644 wso-backend.1 /usr/share/man/man1
.\" gzip /usr/share/man/man1/wso-backend.1
.TH WSO 1 "Ver. 2.0" "6 June 2025"

.SH NAME
wso-backend \- run the WSO server
.sp

.SH SYNOPSIS
.B wso-backend
.RI [--config]  \fIfile...
.sp

.SH DESCRIPTION
Running \fBwso-backend\fP starts the server for WSO, which will open port \fI8080\fP for documentation and begin accepting requests on port \fI80\fP. For more information please read the documentation online.
.sp

.SH OPTIONS
The options for \fBwso-backend\fP are as follows:
.TP
\-\-config
Pass a \fIfile\fP which contains valid configuration data for the server\&.
.sp

.SH HOMEPAGE 
.I https://github.com/WilliamsStudentsOnline/wso-go
.sp

.SH SEE ALSO
\fIhttps://wso.williams.edu\fP (main prod server)
.sp
\fIhttps://wso-dev.williams.edu\fP (dev server)
.sp

.SH BUGS
Yes. See the issue tracker on GitHub for more information.
.SH AUTHOR
Williams Students Online
