##### WSO-Config WSO 2.0 #####

# might want to make this more or less permissive, depending on host.
sysctl_hardening:
  - { key: kernel.printk, value: "3 3 3 3" } # makes it so much less noisy w/ firewall
  - { key: kernel.kptr_restrict, value: 2 } # no more kernel pointers
  - { key: kernel.randomize_va_space, value: 2 } # randomize memory
  - { key: kernel.dmesg_restrict, value: 1 } # no more dmesg without root
  - { key: dev.tty.ldisc_autoload, value: 0 } # disable weird old vulnerable feature
  - { key: kernel.kexec_load_disabled, value: 1 } # may want to disable if kexec speeds up boots
  - { key: kernel.sysrq, value: 0 } # nobody should be able to use it
  - { key: net.ipv4.conf.all.rp_filter, value: 1 } # stop IP spoofing
  - { key: net.ipv4.conf.default.rp_filter, value: 1 } # stop IP spoofing
  - { key: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 } # no ping! turn on if needed
  - { key: net.ipv4.conf.all.accept_source_route, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.conf.default.accept_source_route, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.conf.all.accept_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.conf.default.accept_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.conf.all.secure_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.conf.default.secure_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv6.conf.all.accept_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv6.conf.default.accept_redirects, value: 0 } # disable ICMP redirects
  - { key: net.ipv4.tcp_timestamps, value: 0 }  # no TCP timestamps, they're a privacy risk
  - { key: kernel.yama.ptrace_scope, value: 2 } # only very select processes can ptrace
  - { key: vm.mmap_rnd_bits, value: 32 } # increase ASLR memory protection
  - { key: fs.protected_symlinks, value: 1 } # no symlinks in dangerous directories
  - { key: fs.protected_hardlinks, value: 1 } # no symlinks in dangerous directories
  
  
