##### WSO-Config WSO 2.0 #####

# this may or may not be on by default.
# might want to make this more or less permissive, depending on host.
sysctl_hardening:
  - { key: kernel.printk, value: "3 4 1 3" } # makes it so much less noisy w/ firewall
  - { key: kernel.kptr_restrict, value: 2 }
  - { key: kernel.randomize_va_space, value: 2 }
  - { key: kernel.dmesg_restrict, value: 1 }
  - { key: net.ipv4.conf.all.rp_filter, value: 1 }
  - { key: net.ipv4.conf.default.rp_filter, value: 1 }
  - { key: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
  - { key: net.ipv4.conf.all.accept_source_route, value: 0 }
  - { key: net.ipv4.conf.default.accept_source_route, value: 0 }
  - { key: net.ipv4.conf.all.accept_redirects, value: 0 }
  - { key: net.ipv4.conf.default.accept_redirects, value: 0 }
  - { key: net.ipv4.conf.all.secure_redirects, value: 0 }
  - { key: net.ipv4.conf.default.secure_redirects, value: 0 }
  - { key: net.ipv6.conf.all.accept_redirects, value: 0 }
  - { key: net.ipv6.conf.default.accept_redirects, value: 0 }
