##### WSO-Config WSO 2.0 #####

# installs all the things not included, but that one expects to have
# kernel compilation packages are installed in fresh_kernel, not here
- name: Install core packages
  ansible.builtin.dnf:
    name: "{{ core_packages }}"
    state: present
  vars:
    core_packages:
      - vim
      - emacs-nox
      - nano
      - curl
      - wget
      - git
      - htop
      - ftp
      - tree
      - setools
      - fuse
      - unzip
      - netcat
      - nmap      
      - fastfetch
      - ncdu      

# define these in the host_vars section
- name: Install machine-specific packages
  ansible.builtin.dnf:
    name: "{{ machine_packages }}"
    state: present
  when: machine_packages is defined

# absolutely needed for packages we'll install later not found in repos
- name: Create out-of-repo package directory
  ansible.builtin.file:
    path: /root/ansible
    state: directory
