##### WSO-Config WSO 2.0 #####

- name: Ensure firewalld is installed and enabled
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Set default zone to public
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    state: enabled
    zone: public

- name: Allow loopback
  ansible.builtin.command: >
    firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i lo -j ACCEPT

- name: Allow SSH
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled

- name: Allow HTTP
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled

- name: Allow HTTPS
  ansible.posix.firewalld:
    service: https
    zone: public
    permanent: true
    state: enabled

- name: Allow NTP
  ansible.posix.firewalld:
    port: 123/udp
    zone: public
    permanent: true
    state: enabled

- name: Allow Grafana
  ansible.posix.firewalld:
    port: 3000/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Prometheus
  ansible.posix.firewalld:
    port: 9090/tcp
    zone: public
    permanent: true
    state: enabled

# for testing, disable in prod
- name: Allow Prometheus Node Exporter
  ansible.posix.firewalld:
    port: 9100/tcp
    zone: public
    permanent: true
    state: enabled

- name: Allow Webmin
  ansible.posix.firewalld:
    port: 10000/tcp
    zone: public
    permanent: true
    state: enabled

- name: Allow Jenkins
  ansible.posix.firewalld:
    port: 8080/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname in ['wso_prod', 'wso_dev']

- name: Allow Minecraft BlueMap
  ansible.posix.firewalld:
    port: 8100/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Mailman web interface
  ansible.posix.firewalld:
    port: 8000/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Mailman SMTP (inbound mail)
  ansible.posix.firewalld:
    port: 25/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Mailman submission (auth SMTP)
  ansible.posix.firewalld:
    port: 587/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Mailman IMAP/POP
  ansible.posix.firewalld:
    port: 993/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Allow Minecraft
  ansible.posix.firewalld:
    port: 25565/tcp
    zone: public
    permanent: true
    state: enabled
  when: inventory_hostname == 'wso_prod'

- name: Set default target to DROP
  ansible.posix.firewalld:
    state: enabled
    permanent: true
    zone: public
    target: DROP

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
