##### WSO-Config WSO 2.0 #####

- name: Install apache
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Enable and start apache
  ansible.builtin.systemd:
    name: httpd
    enabled: yes
    state: started
