##### WSO-Config WSO 2.0 #####

- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present

- name: Enable and start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started

- name: Configure SSH jail
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/sshd.conf
    content: |
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/secure
      maxretry = 5
      bantime = 600
